install.packages("coda")
library(coda)
d = read.csv("out.tsv", header = TRUE, sep='\t')
d2 = read.csv("out2.tsv", header = TRUE, sep='\t')
hwd = read.csv("huge-window-out.tsv", header = TRUE, sep='\t')
twd = read.csv("tiny-window-out.tsv", header = TRUE, sep='\t')
mh.draws = coda::mcmc(d)
hw.mh.draws = coda::mcmc(hwd)
tw.mh.draws = coda::mcmc(twd)
plot(d$Iter, d$sigma, type="l")
plot(hwd$Iter, hwd$mu, type="l")
plot(twd$Iter, twd$mu, type="l")
summary(mh.draws)
summary(hw.mh.draws)
summary(tw.mh.draws)
plot(mh.draws)
plot(hw.mh.draws)
plot(tw.mh.draws)
coda::autocorr.plot(mh.draws)
coda::autocorr.plot(hw.mh.draws)
coda::autocorr.plot(tw.mh.draws)
