install.packages("coda")
library(coda)
d = read.csv("out.tsv", header = TRUE, sep='\t')
d2 = read.csv("out2.tsv", header = TRUE, sep='\t')
hwd = read.csv("huge-window-out.tsv", header = TRUE, sep='\t')
hwd2 = read.csv("huge-window-out2.tsv", header = TRUE, sep='\t')
twd = read.csv("tiny-window-out.tsv", header = TRUE, sep='\t')
twd2 = read.csv("tiny-window-out2.tsv", header = TRUE, sep='\t')
plot(d$mu, type="l")
plot(hwd2$mu, type="l")
plot(twd$mu, type="l")
mh.draws = coda::mcmc(d)
mh.draws.2 = coda::mcmc(d2)
hw.mh.draws = coda::mcmc(hwd)
hw.mh.draws.2 = coda::mcmc(hwd2)
tw.mh.draws = coda::mcmc(twd)
tw.mh.draws.2 = coda::mcmc(twd2)
summary(mh.draws)
summary(hw.mh.draws)
summary(tw.mh.draws)
coda::autocorr.plot(mh.draws)
coda::autocorr.plot(hw.mh.draws)
coda::autocorr.plot(tw.mh.draws)
plot(mh.draws)
mh.list <- coda::mcmc.list(list(mh.draws, mh.draws.2))
coda::gelman.diag(mh.list)

hw.mh.list <- coda::mcmc.list(list(hw.mh.draws, hw.mh.draws.2))
coda::gelman.diag(hw.mh.list)
coda::gelman.plot(hw.mh.list)
